### ISSUE TITLE
Adding browse and search

### ISSUE THREAD

**Issue by taxiyoshida** [saurabhmdh/news#3]
### Requirement
- Search 
- Putting articles at random in "Trending" and "Magazine" carousel
- Button of "Your Top Genre"
- Translation to Japanese

### Mockup
- Japanese
https://drive.google.com/open?id=1EZhrXbXI1r9uLqXNaoevL6imUp9aOCto

- English
https://drive.google.com/open?id=1ARNl-H8rHobfqzJ9Uonl_rikZY6pEPG6

### Translation (this is not direct translation) 
- Trending > 話題の記事
- Leverage Wisdom of Crowds > 群衆の知恵を活用する
- Magazines > 編集者のおすすめ
- Enjoy a little of everything you love > 新しい知的発見の機会に
- Your Top Genres > ジャンル
- "Magazines" meant "self-generated magazines based on machine learning" but this feature is  supposed to be built 1-2 years later. So I change it to "Editor's Pick (編集者のおすすめ)"

### Tag name for "Your Top Genre" or "ジャンル" 
(tag name: tag url)
- DIgital Marketing: /digital-marketing
- Digital Economy: /digital-economy
- Internet: /Internet
- Southeast Asia: /southeast-asia
- India: /india
- China: /china

**Comment by saurabhmdh** [comment]
Amazing description, I will work on this.

**Comment by saurabhmdh** [comment]
This issue has been fixed on version v1.0.2, Please verify this.
